name: AD-B2C custom policies release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Upload AD B2C branding files
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.7
        with:
          connection_string: ${{ secrets.AD_B2C_BRANDING_ASSETS_STORAGE_ACCOUNT_CONN_STR }}
          container_name: ad-b2c-branding
          source_folder: src/ad-b2c-templates/ad-b2c-custom-policies-generic/branding/
          destination_folder: branding
          clean_destination_folder: true
    
