name: Code samples build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7
    - name: Build identity developer templates solution
      run: dotnet build ./ConsoleApp1/ConsoleApp1.sln --configuration Release
